# Generated by Django 4.2 on 2023-10-03 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makenote_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Person',
        ),
    ]
