# Generated by Django 4.2.6 on 2023-10-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makenote_app', '0003_note_delete_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='description',
            field=models.TextField(max_length=200),
        ),
    ]
